global:
  # Gardener API server configuration values
  apiserver:
    clusterIdentity: gardener-local
    caBundle: |
      -----BEGIN CERTIFICATE-----
      MIIC/DCCAeSgAwIBAgIUQAP7IWCZPkoMj8PUKHSsd1J1sEAwDQYJKoZIhvcNAQEL
      BQAwFjEUMBIGA1UEAxMLZ2FyZGVuZXItY2EwHhcNMjIxMjA1MDc0MDAwWhcNMjcx
      MjA0MDc0MDAwWjAWMRQwEgYDVQQDEwtnYXJkZW5lci1jYTCCASIwDQYJKoZIhvcN
      AQEBBQADggEPADCCAQoCggEBAMzAd3f7rG9xL9BvX1WxW5HZyLgG/htD1uUJSx+J
      8WNKqkLxXG6Bw2A3a5KD7D4gjEgXXfUG+ZTFS7cdFJvQleAnzXYzAcOEI4Ycq2Wt
      AxvYLjlQAp0AurhT3BFk8MHrQcourrOmnJjQgB8OfGj1c0aglEy/d8g9nXswDmD7
      L1q6o6sWGN7/YG57r/hjQGMlcbtpzMBXBOBkkqrCiurOxZG/uYBq44EHNV+r75xo
      4Dcy3mHVwVaBxrtPAHafRIVHJjmhHWKr37DtK7M8tmvMhDgqhPjqw4bz5dDRwFgn
      tb/Tt+3o4ChQGxm5lGwTKkDO1b12xpiupd3+YA4BKzizAUsCAwEAAaNCMEAwDgYD
      VR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFK2ciiwarNAi
      ZEo9fnZ159LvQYD7MA0GCSqGSIb3DQEBCwUAA4IBAQCBlolkHDNBaEqyPQjXT9pM
      xfJlO3g1LNrog0eIkay66b3dyukkVqBD3YdvHN+dz4Bthz54VAbvsACdl643HCrg
      zZW7gmFuXuBoX4HiX/f8KCUnXiEL+2NXbViWpsRC3efNOJeezin9G1bUKp24VRhe
      ExqUfFj8qQYt3TER3CXUCe2SmKM6vd+lyVvglwwHxWqebJ7HJJlACIpvq3UBFc0M
      1q5o0/5WLkqhK5RIxnx2QTyg6SM1FBzprng5os8vL5DMTuqS7+gDUdMU+WyjH6aG
      Oln8S2QCk3rgGVnX1hbahgtFU4LONPHQB06My2rLECsR4AGssZnrYNgEfwtGl0KV
      -----END CERTIFICATE-----
    tls:
      crt: |
        -----BEGIN CERTIFICATE-----
        MIID+zCCAuOgAwIBAgIUKmAqZ7XpIrE+nOqhGr1OgNvG2GYwDQYJKoZIhvcNAQEL
        BQAwFjEUMBIGA1UEAxMLZ2FyZGVuZXItY2EwHhcNMjIxMjA1MDc1MDAwWhcNMzIx
        MjAyMDc1MDAwWjAdMRswGQYDVQQDExJnYXJkZW5lci1hcGlzZXJ2ZXIwggEiMA0G
        CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCpA1FLF2bxH8hV+ShxsK4p1YVTAZVn
        gwrree+b51m6ces4H0a7f6WyGim0+YNgqn0hXNnjOUkTM+4KV9rCOloeLHNITsgS
        9pkkySaeQKvIfBEsVePDE06KuZKgbChC+GKUTPw3EP2UcyfBa8SKAnCZFKhYAmVb
        52oSaoPV89ydS877Y5aaNCkH7EdnuWcPrHtN5gFPgbfHt5C5Mbl6qGDxgBKqhMYI
        NxG8Z/dCfqzH25OTWCtQx3OUb6wMzlb42N3eqyslRZpkziOXlCr1AxxQAC0wkFfD
        KE7gNNvjWzHjMlWl9BtK20EbTqLbCPQ8KocbVlogSFoP/+ZpIxqYoRePAgMBAAGj
        ggE4MIIBNDAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDAYD
        VR0TAQH/BAIwADAdBgNVHQ4EFgQU/Vlhy0re/4FoB6965D21eSFNlOAwHwYDVR0j
        BBgwFoAUrZyKLBqs0CJkSj1+dnXn0u9BgPswgb4GA1UdEQSBtjCBs4IJbG9jYWxo
        b3N0ghJnYXJkZW5lci1hcGlzZXJ2ZXKCGWdhcmRlbmVyLWFwaXNlcnZlci5nYXJk
        ZW6CHWdhcmRlbmVyLWFwaXNlcnZlci5nYXJkZW4uc3ZjgiVnYXJkZW5lci1hcGlz
        ZXJ2ZXIuZ2FyZGVuLnN2Yy5jbHVzdGVygitnYXJkZW5lci1hcGlzZXJ2ZXIuZ2Fy
        ZGVuLnN2Yy5jbHVzdGVyLmxvY2FshwR/AAABMA0GCSqGSIb3DQEBCwUAA4IBAQAY
        XqFjuaMRGiRR8RE8nO9LE+S6GXT0tuwO9eBsLlG9ywEf20ZuskGWiJJN3u+Uc0XL
        4z37M3+Xztj+6I1UlQc+refWMHCsDmwKohf8B2RsgaR+BZAKGpW684ZVh0Ktlk8Y
        OCyzNjO7Z8TY+UqWyvcpD5JqNzKG9DztvobS3BFVFEkq23Ua2J1ghw+2NXrohqpJ
        GjcAeU4XWd8HaArOuyzRKrpUFkVEaa3Ccbs85OBTr2CS9qD4AOgk1+GX70PjGaFV
        rY3BuHWDaZ5PU89qvCzNB6TI3Bk+2rvrV8oJ/jqnShmiIKTudqfdp1j51R+TEMow
        bsid90r1hQA7y+cRc+2J
        -----END CERTIFICATE-----
      key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEpAIBAAKCAQEAqQNRSxdm8R/IVfkocbCuKdWFUwGVZ4MK63nvm+dZunHrOB9G
        u3+lshoptPmDYKp9IVzZ4zlJEzPuClfawjpaHixzSE7IEvaZJMkmnkCryHwRLFXj
        wxNOirmSoGwoQvhilEz8NxD9lHMnwWvEigJwmRSoWAJlW+dqEmqD1fPcnUvO+2OW
        mjQpB+xHZ7lnD6x7TeYBT4G3x7eQuTG5eqhg8YASqoTGCDcRvGf3Qn6sx9uTk1gr
        UMdzlG+sDM5W+Njd3qsrJUWaZM4jl5Qq9QMcUAAtMJBXwyhO4DTb41sx4zJVpfQb
        SttBG06i2wj0PCqHG1ZaIEhaD//maSMamKEXjwIDAQABAoIBAQCXaNBv/AQNqVJY
        qsAvsX8lHRK2fOmydLPYpkEgos5AeAOoIGTGXiE7f7KzXP/0HmfA9qR/qfcsC86J
        V5EzhQDsnRedxG36hw5E5SsChJ8gGP1tgXhsbyRipMKVkq8y57+waZNdZYw2bD9G
        SNwmYu8qRFZXmbXh8luVKfT3O+L8ydNpn2YLMQ8e0yqVZz+KWfcs+zbo+4UnfbKK
        SYkybnkdUepyhYOpGJYabL6SRkPKC4TO7EAGKzIdvDQhNW1SbEocxFXvB2ReYtlu
        I8dZTYAWlKcidC/+rYfFM3BZ114UKDoCcV0ao7lvWVb5TQFJ0R0MobF+30EKfSXN
        nXIwI5t5AoGBANJNIuobn1+RY61DPHbUHeq02xG3eiuq0H89C5WMBWHNL0fx8fuL
        9GLDWyShNiu+Zu7DxCtHAFRsXhkL+MIqFpjbrQdt1H5NlKE90l9BaadWX3CCAbUA
        +fBkWArXIApbLWE/KyCYO1DfgYRDUvwtUbaT7FPjktPuMqNyaCAf29pjAoGBAM29
        WVU+7bFmGAeHJnSlFokRV8P+c7fTRSoRkZ7ju6FUe/FdYsCVsphbEABg7f3nFgnB
        VAndVPd7aStynW9p/RwsKCGDVHlAGPgAWyR11xjtjiMWn8ClF0vrLmD0jANP4guJ
        9nJQorPZ7PdNm15KlPSFNF/JkQ8NX26ZSGcPJF/lAoGADIzL45qoZSShBSr5BcJc
        0q/eTu1bHhYAgUdcVJ1ZiN+czbdTkIZmnCo6WzI/sFaZf/Aw2cBP9bnN18LOIpAu
        bwrVBZd5UdxBXWn6DvMxYeoWofkwLuQTBlSGqIb0A4ozaBVD9pr/FzFvYjw+TIxL
        zxB+zvbKwVj6rqRaMGiWTy8CgYASkz7miGjzdFFFFLmvHFydgXhYFLgj56o98xof
        q1X8aeFK2HCbDKj0Qnx+XEIAg4Wk2dSZk2chdP340z9NmNcmXQI+jFnrHJNkiLux
        3gXOlVwY5OkFfqJM0237iPi/L84r1ofuqEMYU9umNFaLu9YZAZHJ+CvlnQJ5vNMh
        oudY1QKBgQCP8gd0r40mILcMT/iRhqCWRb0n6yHSqZVz5LiCRWzVdKiUp+gCycai
        CeeyB+NBjO0VbeHjBOBn17ALmSMRviiXh3Rof9OINtDUi6AO/6rupModSK4LOfbY
        mcPMHv3WfSMaoYp7zjlFrW5O0KiCXEJGbq1BXmbvBMvwT88l1BgMnQ==
        -----END RSA PRIVATE KEY-----
    etcd:
      servers: https://etcd-client.garden.svc:2379
      caBundle: |
        -----BEGIN CERTIFICATE-----
        MIIC/DCCAeSgAwIBAgIUQAP7IWCZPkoMj8PUKHSsd1J1sEAwDQYJKoZIhvcNAQEL
        BQAwFjEUMBIGA1UEAxMLZ2FyZGVuZXItY2EwHhcNMjIxMjA1MDc0MDAwWhcNMjcx
        MjA0MDc0MDAwWjAWMRQwEgYDVQQDEwtnYXJkZW5lci1jYTCCASIwDQYJKoZIhvcN
        AQEBBQADggEPADCCAQoCggEBAMzAd3f7rG9xL9BvX1WxW5HZyLgG/htD1uUJSx+J
        8WNKqkLxXG6Bw2A3a5KD7D4gjEgXXfUG+ZTFS7cdFJvQleAnzXYzAcOEI4Ycq2Wt
        AxvYLjlQAp0AurhT3BFk8MHrQcourrOmnJjQgB8OfGj1c0aglEy/d8g9nXswDmD7
        L1q6o6sWGN7/YG57r/hjQGMlcbtpzMBXBOBkkqrCiurOxZG/uYBq44EHNV+r75xo
        4Dcy3mHVwVaBxrtPAHafRIVHJjmhHWKr37DtK7M8tmvMhDgqhPjqw4bz5dDRwFgn
        tb/Tt+3o4ChQGxm5lGwTKkDO1b12xpiupd3+YA4BKzizAUsCAwEAAaNCMEAwDgYD
        VR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFK2ciiwarNAi
        ZEo9fnZ159LvQYD7MA0GCSqGSIb3DQEBCwUAA4IBAQCBlolkHDNBaEqyPQjXT9pM
        xfJlO3g1LNrog0eIkay66b3dyukkVqBD3YdvHN+dz4Bthz54VAbvsACdl643HCrg
        zZW7gmFuXuBoX4HiX/f8KCUnXiEL+2NXbViWpsRC3efNOJeezin9G1bUKp24VRhe
        ExqUfFj8qQYt3TER3CXUCe2SmKM6vd+lyVvglwwHxWqebJ7HJJlACIpvq3UBFc0M
        1q5o0/5WLkqhK5RIxnx2QTyg6SM1FBzprng5os8vL5DMTuqS7+gDUdMU+WyjH6aG
        Oln8S2QCk3rgGVnX1hbahgtFU4LONPHQB06My2rLECsR4AGssZnrYNgEfwtGl0KV
        -----END CERTIFICATE-----
      tls:
        crt: |
          -----BEGIN CERTIFICATE-----
          MIIDNjCCAh6gAwIBAgIUEx6YTFYzB2Rgxz0YmC4ozWKihCgwDQYJKoZIhvcNAQEL
          BQAwFjEUMBIGA1UEAxMLZ2FyZGVuZXItY2EwHhcNMjIxMjA1MDc0NjAwWhcNMzIx
          MjAyMDc0NjAwWjAdMRswGQYDVQQDExJnYXJkZW5lci1hcGlzZXJ2ZXIwggEiMA0G
          CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCwllNRSTtKxRRCYgtUeNYAZ9eJCSH7
          rEYnBxrUSzj5u4diaWC5e+0FhCjeM2FuR6lz8Yxn061uQoC60RcstzlQmemAx4Vs
          +HB72gep3xvoZNp7u63bLs+6NkhDntnzyMCwjhz+H+ECEnu4w8Es5EiZn8IWfYQo
          wNjZTeh+amtcpcXBA6wqNKIWSSTJ/ig5s4HCsf+7V360b406cyLkUSzXMzLDOPtj
          8mirXjobdgV2Fa47lK9Wae8kWNAzP/QSlECccj8s/XWMrRyisVjn+vNYH9JvnuNa
          SJE+P5qEMyJC5yyJPDSmw9/9E3kfDN5bEGKSrFUs2ER2fJf18ENDkIQHAgMBAAGj
          dTBzMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAKBggrBgEFBQcDAjAMBgNVHRMB
          Af8EAjAAMB0GA1UdDgQWBBT2/B7wWRsE4rKQh0EKqGFBLMPFADAfBgNVHSMEGDAW
          gBStnIosGqzQImRKPX52defS70GA+zANBgkqhkiG9w0BAQsFAAOCAQEAAxdHKkuD
          BKNPoIFMBYhq7SB5UY4MyXS5/RO8RyvB5d9kZ0+XnWD7+Izp3E09zjI5n6iQ5jMy
          rcyvv47aqzN+NnaXcr4mvMqYoZB3vwtd0/cB6h6rS149soFKNw8XoDiKoWH/l3Ve
          MWHTZrE8B/EMo0ABaM2d+ENPSxzqc3+UoCldgAwPkWt1ZBSBdLf0tIDF/IS5AMXx
          V1I7s1hgDSoR0bU8H70HOZTmJB5J06ntRxQXqZAluZAKcXJvmTT414MOk4PeXTMZ
          3jvTg+joPNjQHn6ctENxZtont+BLVZTMOzq5h6MO1HZbRoCK65ZPe3LnpYpSnZRa
          AyB2epoNeuP9zA==
          -----END CERTIFICATE-----
        key: |
          -----BEGIN RSA PRIVATE KEY-----
          MIIEpQIBAAKCAQEAsJZTUUk7SsUUQmILVHjWAGfXiQkh+6xGJwca1Es4+buHYmlg
          uXvtBYQo3jNhbkepc/GMZ9OtbkKAutEXLLc5UJnpgMeFbPhwe9oHqd8b6GTae7ut
          2y7PujZIQ57Z88jAsI4c/h/hAhJ7uMPBLORImZ/CFn2EKMDY2U3ofmprXKXFwQOs
          KjSiFkkkyf4oObOBwrH/u1d+tG+NOnMi5FEs1zMywzj7Y/Joq146G3YFdhWuO5Sv
          VmnvJFjQMz/0EpRAnHI/LP11jK0corFY5/rzWB/Sb57jWkiRPj+ahDMiQucsiTw0
          psPf/RN5HwzeWxBikqxVLNhEdnyX9fBDQ5CEBwIDAQABAoIBAQCNnwITHvg+bvBg
          jOEpTf/TM3TYokpu3SsmAbyypeF757ocYwb/uzPMSMG98tcg6rgsFHzWiB1/YDZ9
          nVNIuWluCwIKFfob+uO7cJDU2+o15yySL2KvdkuCvCYYlT2XFlnzPwZhiI+cadZv
          yA8VQcA39Lhj8SYcyQ0guirLt+2CzttNu9VG79QT6HB1wmoIeqwj5METsZwqcGov
          E/VHDnzq78GTazbGivEpFPTbXzEOzgNPUpYe5e8oFWR2YamLn2rO5TNYCHavcRT8
          9Bwa3iw8ZGfCbPEUGx/nwhA+CdZ3xQWW+O/uDBLqGt0E3Q+L6VKA0JxLoQyQ4uV5
          scoXyuIBAoGBANL8ktth3oFLNun2MM0V4DvvHvIkpOUgIwMAArAhBvOuQmCRo38K
          kKmT/THe0fi+SbbLuuOFfemBC3Yp7U0O11LNg7PkwPOki/lj8cndNP74dSlemYBs
          AwstvDtYRlwo16vXjQqEsufCMiJnKh4nfKHePiv6deoEfG15I0Wf7h9xAoGBANZC
          9tcoyfTSkcen1e3oL5joJMIIik+QpyZnBjVg2JT+VEbW45mQeE8CJvwAEcrgexCf
          DDC6a1583ErIYJorXFelPT4RKQf8Wnj6SAxH0f/HJ4/coRLQSXqETrrlCZYC3AD8
          gRMIIpO/hyOY+fPTSlm1vW4G/XjUHftvNJ6EmA73AoGBALmxMk+DQ6Hn4NzpoOnf
          ZwtY2ZOkTLycHDR3veXmK4gsxp7Xj14wnkGhziYmRgb280m+5S16P+dTfBLzs7cu
          aLSnzFJ38pp9J/TG0fcoiYwegH94kwFEDym3hwN0HfjeuXK0s52eTRdNA3Lj+V2w
          wzBzuaRbO4xLhneTNkgBCkMBAoGBAJybaYyudZ8K4h8K3+T6lv+ufl+Mmnu5gVMi
          bnlJhkSw+KymmMk/vZASRKhg7KBbH9hwSBq9x4jSvrmyaFmHZAFz96WMKW961i4i
          0dKYFDheOt5+JwV3VJ3GYz1b93u8L05RQY7FnXBcx8wPHnNHdsrHeeQYG+DbOebz
          y4Qp6nLVAoGAXQvKz2wiyFus/fE4Amg9/UI4gtkyTEGbZ/EsA8TSPaIqBnQOYPjv
          NgAxasD6yZVVIIENe+4YJvK+aEt2PuNgIKyEIurpVy4zJ66fgA90bK1I+hIWwH49
          adePGltijSbPOCOx1MSV///pjk7CCblYNa3/etxMBXhTlc6lRuoLp10=
          -----END RSA PRIVATE KEY-----
    # speed-up re-deploying of gardener-apiserver
    minReadySeconds: 0
    enableAdmissionPlugins:
    - ShootVPAEnabledByDefault
    # disable audit log
    audit:
      log:
        path: ""
        maxBackup: 0
        maxSize: 0
        policy: ""
    featureGates:
      SeedChange: true
      HAControlPlanes: true
    resources: {}

  # Gardener admission controller configuration values
  admission:
    enabled: true
    service:
      clusterIP: fc00:10:96::1000
    seedRestriction:
      enabled: true
    config:
      server:
        webhooks:
          bindAddress: 0.0.0.0
          port: 2719
          tls:
            caBundle: |
              -----BEGIN CERTIFICATE-----
              MIIDJjCCAg6gAwIBAgIUUaSpEaJfy6lXiwagtBuGsRr0HtEwDQYJKoZIhvcNAQEL
              BQAwKzEpMCcGA1UEAxMgZ2FyZGVuZXItYWRtaXNzaW9uLWNvbnRyb2xsZXItY2Ew
              HhcNMjIwNTAzMDY0MjAwWhcNMjcwNTAyMDY0MjAwWjArMSkwJwYDVQQDEyBnYXJk
              ZW5lci1hZG1pc3Npb24tY29udHJvbGxlci1jYTCCASIwDQYJKoZIhvcNAQEBBQAD
              ggEPADCCAQoCggEBAK/aKhVzDGDt5jnIDhHIqgdJpigoBIR0qhRDW0B2GKAURizO
              p/nJzDA98Pjn6XEs6H93u7pGCSi/TE0hyDGwajDKm55xPE4/KSrnb1xubZ9FSBwP
              SYL801yWhrBlCVBUAxDsQ3rbJBH17B6zsZ9UYzAEz+gncm4XYCv02V6Zt6N8HjtK
              T0n0pRiBJBwjQVPXNHUyzZhvlzCDa/gCu5GvLQ1kORcgji9nE6KUbARySCm4clFD
              l4r5Yij8Zp8D8fo0WhmA5+ZEmubJG8SnGxxGpAtwOddjRHZs2YMCJrK8IIasg5AH
              uK/OR2o1uVbpXZLIaC1YyNPgGqj7ar7pUReDBQ0CAwEAAaNCMEAwDgYDVR0PAQH/
              BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFEW+SbKZtbxUpiyOp90M
              9PlXJ2u0MA0GCSqGSIb3DQEBCwUAA4IBAQA8VldEkYcdkvake9SsaSh4DV2V0uJ/
              atElLeGva1YNVoG99YsKGjJbJw+LrIdsguKhKbir7fS/rRAXxKY6cMyc+F0uwbGZ
              RtpaqXOEh/r7fCbuyt2KxAnCvIIbnx0L+TETPoagWsb56TGT7us0mjj9CH8zYlAv
              eYK3m5QDZWQTDzSCunWwQToQPIUibyFkR+BnIF8H0NJ61oDsZP4VH+rOiUaj0v3H
              KKWOXzAusn7RCzXAemXVD02Dx0urpt7z/O00415lvj7MUPfRQJscyySpnK9hkdOs
              1aTC6iwUjozjF1Fe2mANbKWERNaZIoVaTAVhtgMYL0jf2Zr6oZkX22dT
              -----END CERTIFICATE-----
            crt: |
              -----BEGIN CERTIFICATE-----
              MIID6DCCAtCgAwIBAgIUJl4x4/SAELgFsXIGJcWlt9YF70kwDQYJKoZIhvcNAQEL
              BQAwKzEpMCcGA1UEAxMgZ2FyZGVuZXItYWRtaXNzaW9uLWNvbnRyb2xsZXItY2Ew
              HhcNMjIwNTAzMDY0NDAwWhcNMzIwNDMwMDY0NDAwWjAoMSYwJAYDVQQDEx1nYXJk
              ZW5lci1hZG1pc3Npb24tY29udHJvbGxlcjCCASIwDQYJKoZIhvcNAQEBBQADggEP
              ADCCAQoCggEBAKupPy1XWFSZjbdihItv7RSP7baCAtrDNo0SRXjIk9+tE0rsa1lm
              f8N5IYMl9uKIhHLUbLeoetryrDqm75rUw9DbwB0W0w0Jk16WBFH7E5bQ5nbhJDbs
              s4PfRWpu03p0uEI8dY5XkW3F1hIGlt4kOBOngGLorLe6lF96bbc/wtZCDiEN9JbK
              X1k45fDqIkoO3SbzIohKSe+JMmgD5ZxeqSvzcGKzLtfavShUcQBmGKsnTF1hiN0F
              47+b7HqfAvWwNPiwXSstmlkYn47wHoSTElMHVq17OsCnPWl8ygYQxdsd4p0ETCij
              ujwWemUeW1KMEjs2EM7Wj7NOjcdOQGNSQKkCAwEAAaOCAQUwggEBMA4GA1UdDwEB
              /wQEAwIFIDATBgNVHSUEDDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMB0GA1Ud
              DgQWBBTg6DoeCYVVNqetjpL57+7vjInTCTAfBgNVHSMEGDAWgBRFvkmymbW8VKYs
              jqfdDPT5VydrtDCBiwYDVR0RBIGDMIGAgglsb2NhbGhvc3SCHWdhcmRlbmVyLWFk
              bWlzc2lvbi1jb250cm9sbGVygiRnYXJkZW5lci1hZG1pc3Npb24tY29udHJvbGxl
              ci5nYXJkZW6CKGdhcmRlbmVyLWFkbWlzc2lvbi1jb250cm9sbGVyLmdhcmRlbi5z
              dmOHBH8AAAEwDQYJKoZIhvcNAQELBQADggEBAFUkROHqmJmgas6Df3Bj9L0IiZsS
              kZNqa+Qu0o0/5b7ePDAFHg9uiobwchGIfLUvUWovJTPa89jm1yBoVZ6aMIvqQqhg
              jwmof/BtR/nh1MSQjSx+O0raJjVk7xj0Z8fhGs44OAbzsoMec/yldiMLiP0+ybVp
              BGd+9Pcl5/pkngfcLtxPB0Vu/CWaLXCCOa/sOoWOz9kKGLuiizBKIK8ESL7Z0Jtm
              rfqIQ9A0r/d+jjWe3l3+sl56lFQ7agri8O40rBMyDE66BQfvER4ndicjeX4SjaH8
              R/y7S53DvrJ3xsogoQ60ETmqez9OJF+dcdECxqw8J1lebkbD8yz9b03cK3o=
              -----END CERTIFICATE-----
            key: |
              -----BEGIN RSA PRIVATE KEY-----
              MIIEowIBAAKCAQEAq6k/LVdYVJmNt2KEi2/tFI/ttoIC2sM2jRJFeMiT360TSuxr
              WWZ/w3khgyX24oiEctRst6h62vKsOqbvmtTD0NvAHRbTDQmTXpYEUfsTltDmduEk
              Nuyzg99Fam7TenS4Qjx1jleRbcXWEgaW3iQ4E6eAYuist7qUX3pttz/C1kIOIQ30
              lspfWTjl8OoiSg7dJvMiiEpJ74kyaAPlnF6pK/NwYrMu19q9KFRxAGYYqydMXWGI
              3QXjv5vsep8C9bA0+LBdKy2aWRifjvAehJMSUwdWrXs6wKc9aXzKBhDF2x3inQRM
              KKO6PBZ6ZR5bUowSOzYQztaPs06Nx05AY1JAqQIDAQABAoIBADsbbbuJBcsrjFaG
              v6jbg0C/RlS/c4gsC46Lqgwq1HACQlBcE6KW3otKHDXyTo41/5Uie8TJaHQXdyJC
              9OHVPQ+fewkJIOauU2YQNbCcyWP2zkRExZl761wO9vHs8ziJFCEKfFfk4xhvNITE
              bBJVWlG6LUThZQdmYUx29WxRsh7f01rRwwG8Ce3y7yel49HU0DHlttP/MsNkzQxv
              oLMjD5ETyxnYQghJL3IYdHIODKFrCPCuzpDM3dP8ICFTmiM8yzTb5wISLShaBNv9
              Nx9jXXPG7GBjXV+rrbksstei+IMpmwfJPVLN1OX0v3VCd1qRAUt2gz8kLBphEM+Z
              xoQslWECgYEA2C4Le5M7IDhCQUN/h63HFaj4z0oWxgs9Vyw2TPgNyPWjFJx2Czel
              2Y8BI94KWkzGPu+NBOgo8XM2I08ccJ9eT29O958I396dEIkT+Tx1XmjSUyoU9hwH
              yDU2qUTzgPW782V+Mn7nvuzTSKdOZGySMQAwuau7KMVpPjOte54vAw0CgYEAy0fs
              AzfkJxQcluYJS/8J1obfedFLMaMvDxv8Rv+HRqyThBL69Oz47NGeMQoZJMUqAT+M
              JWSogUwr1jjsGrBFb3G/pfY5Sx1mJjMZ2Nu5on/cBpWH6ysoHtzk0IuAmZHivNqt
              aF7kk1+rrw1/OuK0bitYTlZ1dpnjRyyXMUrJPQ0CgYAN4I7OJPpjrBjctaeHHymr
              g0hNjjT+C5SpduYZdMb1wobweMa/G5hi6eIp2kQR3eHQAnKsAPc34Kx2AcsSk7hr
              IvsPvD7GmDS+7f3BPxdNsy7lNctYrR32xSu4G/wBqESjcD10ol7gC7XYcR0AJ1QP
              HzMBiDugd2O1IX4edF4SNQKBgHv4wNa1n0611Tmx0LmoMDfEyUVhfponCuwMBS7H
              Z5iSZuSFLsdwPd8vd2ow3mSuWY+pUa78VEeGTLW4wUUFe1Mb6+Uq5IYKx+FECN9Y
              IT4Y+/aH+vxQtYcc7+6/JQ6DCeRi+J5OQNgf4HRBpvYijCckCBa+Y6SQ9SrS5uII
              2fGBAoGBAKPqoceWtJNPlT/2F8XWde3B9+Yu4v9deTL9hqMcmd3DSQRlstua6pXn
              2gdfX1KfoWJn/MxI5UKf5RZ2ygmNCTqdLFK/5v7zr4aMw5fSxc9Hf0WuKA8EGzfw
              8dNU6RXARJRSWWKk7wAxSoiNZT/L9VdB0DxZNgZiPBNzdSN6ovgG
              -----END RSA PRIVATE KEY-----
    replicaCount: 2
    resources: {}

  # Gardener controller manager configuration values
  controller:
    config:
      server:
        http:
          bindAddress: 0.0.0.0
          port: 2718
    resources: {}

  # General system configuration
  internalDomain:
    provider: local
    domain: internal.local.gardener.cloud
  defaultDomains:
  - provider: local
    domain: external.local.gardener.cloud
