apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
metadata:
  name: secv6
  namespace: garden
  annotations:
    shoot.gardener.cloud/infrastructure-cleanup-wait-period-seconds: "0"
    shoot.gardener.cloud/cloud-config-execution-max-delay-seconds: "0"
spec:
  seedName: provider-extensions
  cloudProfileName: cloudprofile1
  secretBindingName: my-provider-account # dummy, doesn't contain any credentials
  region: europe-west3
  networking:
    type: calico
    pods: 2002:db8:1::/48
    # Patch ipv6 network after terraform run
    # nodes: 2002:db8:2::/64
    services: 2002:db8:3::/108
    ipFamilies:
      - IPv6
    # TODO(scheererj): Drop this once v1.32 has been released and https://github.com/gardener/gardener-extension-networking-calico/pull/250 is available as release
    providerConfig:
      apiVersion: calico.networking.extensions.gardener.cloud/v1alpha1
      kind: NetworkConfig
  provider:
    controlPlaneConfig:
      apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
      kind: ControlPlaneConfig
      zone: europe-west3-c
    infrastructureConfig:
      apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
      kind: InfrastructureConfig
      networks:
        workers: 10.180.0.0/16
    type: gcp
    workers:
      - name: gcp
        machine:
          type: n1-standard-1
          image:
            name: ubuntu
            version: 22.0.4
        cri:
          name: containerd
        minimum: 1
        maximum: 1 # currently, only single-node clusters are supported
        maxSurge: 1
        maxUnavailable: 0
        volume:
          size: 50Gi
          type: pd-standard
        zones:
          - europe-west3-c
  kubernetes:
    version: 1.24.6
    kubelet:
      serializeImagePulls: false
      registryPullQPS: 10
      registryBurst: 20
      protectKernelDefaults: true
      streamingConnectionIdleTimeout: 5m
